# Assignment 1: Logistic Regression
Welcome to week one of this specialization. You will learn about logistic regression. Concretely, you will be implementing logistic regression for sentiment analysis on tweets. Given a tweet, you will decide if it has a positive sentiment or a negative one. Specifically you will: 

* Learn how to extract features for logistic regression given some text
* Implement logistic regression from scratch
* Apply logistic regression on a natural language processing task
* Test using your logistic regression
* Perform error analysis

We will be using a data set of tweets. Hopefully you will get more than 99% accuracy.  
Run the cell below to load in the packages.

## Import functions and data

In [66]:
# run this cell to import nltk
import numpy as np
import pandas as pd

import nltk
from nltk.corpus import twitter_samples, stopwords
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

import re
import string
from nltk.tokenize import TweetTokenizer
from nltk.stem import PorterStemmer

#from utils import process_tweet, build_freqs
nltk.data.path.append('C:/Users/pulki/OneDrive/Documents/Jupyter/NLP - Deeplearning.ai/nltk_data')

### Prepare the data
* The `twitter_samples` contains subsets of 5,000 positive tweets, 5,000 negative tweets, and the full set of 10,000 tweets.  
    * If you used all three datasets, we would introduce duplicates of the positive tweets and negative tweets.  
    * You will select just the five thousand positive tweets and five thousand negative tweets.

In [12]:
# select the set of positive and negative tweets
all_positive_tweets = twitter_samples.strings('positive_tweets.json')
all_negative_tweets = twitter_samples.strings('negative_tweets.json')

* Train test split: 20% will be in the test set, and 80% in the training set.


In [24]:
# combine positive and negative labels
tweets = all_positive_tweets+all_negative_tweets
len(tweets)

10000

* Create the numpy array of positive labels and negative labels.

In [48]:
labels = np.append(np.ones(len(all_positive_tweets)), np.zeros(len(all_negative_tweets)))

In [49]:
labels

array([1., 1., 1., ..., 0., 0., 0.])

In [128]:
# split the data into two pieces, one for training and one for testing (validation set) 
x_train = all_positive_tweets[1000:] + all_negative_tweets[:-1000]
y_train = labels[1000:9000]
x_test = all_positive_tweets[:1000] + all_negative_tweets[-1000:]
y_test = np.append(labels[:1000], labels[-1000:])

### Process tweet
Define a function `process_tweet()` to tokenize the tweet into individual words, remove stop words and apply stemming.

In [20]:
stopwords_english = stopwords.words('english')
punctuation = string.punctuation

def preprocess_tweet(tweet):
    tweet = re.sub(r'^RT[\s]+', '', tweet)
    tweet = re.sub(r'https?./\/\.*[\r\n]*', '', tweet)
    tweet = re.sub(r'#*', '', tweet)
    
    tokenizer = TweetTokenizer()
    tokens = tokenizer.tokenize(tweet.lower())
    
    clean_tokens = [x for x in tokens if (x not in stopwords_english) & (x not in punctuation)]
    
    stemmer = PorterStemmer()
    return [stemmer.stem(word) for word in clean_tokens]

In [21]:
def build_freq(tweet_list, labels):
    wl_pair = []
    for tweet, label in zip(tweet_list, labels):
        for word in tweet:
            wl_pair.append([word, label])
    
    freq = pd.DataFrame(wl_pair, columns=['vocab', 'label'])
    
    word_freq = pd.DataFrame(freq.groupby('vocab').sum())
    
    freq.label = 1-freq.label
    word_freq['neg'] = freq.groupby('vocab').sum()
    
    return word_freq.convert_dtypes().rename(columns={'label': 'pos'}).reset_index()#.to_dict(orient='list')

In [30]:
import ctypes

x = id(freq_df)
y = ctypes.cast(x, ctypes.py_object).value

type(y)

pandas.core.frame.DataFrame

In [51]:
# test the function below
freq_df = build_freq([preprocess_tweet(tweet) for tweet in x_train], y_train)
freq_df.head()

vocab  pos  neg
0   (-:    2    0
1    (:    0    6
2    ):    7    6
3    );    1    0
4  --->    1    0

## Part 2: Extracting the features

* Given a list of tweets, extract the features and store them in a matrix. You will extract two features.
    * The first feature is the number of positive words in a tweet.
    * The second feature is the number of negative words in a tweet. 
* Then train your logistic regression classifier on these features.
* Test the classifier on a validation set. 

In [141]:
def extract_features(tokenized_tweet):
    '''
    Input: 
        tweet: a list of words for one tweet
        freqs: a dictionary corresponding to the frequencies of each tuple (word, label)
    Output: 
        x: a feature vector of dimension (1,3)
    '''
    return [1] + list(freq_df.loc[freq_df.vocab.isin(tokenized_tweet), ['pos', 'neg']].sum())

In [63]:
# Calling the function on test set
train_features = [extract_features(preprocess_tweet(tweet)) for tweet in x_train]
train_features[:5]

[[1, 2971, 3], [1, 565, 94], [1, 3910, 356], [1, 3849, 165], [1, 625, 5]]

In [67]:
# Training a Logistic Regression Model
lr = LogisticRegression()
lr.fit(train_features, y_train)

LogisticRegression()

In [140]:
# Test with a tweet
print(f'Tweet: {x_test[-1]}. \nPrediction: {lr.predict([extract_features(preprocess_tweet(x_test[-1]))])}')

Tweet: @eawoman As a Hull supporter I am expecting a misserable few weeks :-(. 
Prediction: [0.]


# Part 1: Logistic regression 


### Part 1.1: Sigmoid
You will learn to use logistic regression for text classification. 
* The sigmoid function is defined as: 

$$ h(z) = \frac{1}{1+\exp^{-z}} \tag{1}$$

It maps the input 'z' to a value that ranges between 0 and 1, and so it can be treated as a probability. 

<div style="width:image width px; font-size:100%; text-align:center;"><img src='../tmp2/sigmoid_plot.jpg' alt="alternate text" width="width" height="height" style="width:300px;height:200px;" /> Figure 1 </div>

#### Instructions: Implement the sigmoid function
* You will want this function to work if z is a scalar as well as if it is an array.

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li><a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.exp.html" > numpy.exp </a> </li>

</ul>
</p>



In [10]:
# UNQ_C1 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def sigmoid(z): 
    '''
    Input:
        z: is the input (can be a scalar or an array)
    Output:
        h: the sigmoid of z
    '''
    

### Logistic regression: regression and a sigmoid

Logistic regression takes a regular linear regression, and applies a sigmoid to the output of the linear regression.

Regression:
$$z = \theta_0 x_0 + \theta_1 x_1 + \theta_2 x_2 + ... \theta_N x_N$$
Note that the $\theta$ values are "weights". If you took the Deep Learning Specialization, we referred to the weights with the `w` vector.  In this course, we're using a different variable $\theta$ to refer to the weights.

Logistic regression
$$ h(z) = \frac{1}{1+\exp^{-z}}$$
$$z = \theta_0 x_0 + \theta_1 x_1 + \theta_2 x_2 + ... \theta_N x_N$$
We will refer to 'z' as the 'logits'.

### Part 1.2 Cost function and Gradient

The cost function used for logistic regression is the average of the log loss across all training examples:

$$J(\theta) = -\frac{1}{m} \sum_{i=1}^m y^{(i)}\log (h(z(\theta)^{(i)})) + (1-y^{(i)})\log (1-h(z(\theta)^{(i)}))\tag{5} $$
* $m$ is the number of training examples
* $y^{(i)}$ is the actual label of the i-th training example.
* $h(z(\theta)^{(i)})$ is the model's prediction for the i-th training example.

The loss function for a single training example is
$$ Loss = -1 \times \left( y^{(i)}\log (h(z(\theta)^{(i)})) + (1-y^{(i)})\log (1-h(z(\theta)^{(i)})) \right)$$

* All the $h$ values are between 0 and 1, so the logs will be negative. That is the reason for the factor of -1 applied to the sum of the two loss terms.
* Note that when the model predicts 1 ($h(z(\theta)) = 1$) and the label $y$ is also 1, the loss for that training example is 0. 
* Similarly, when the model predicts 0 ($h(z(\theta)) = 0$) and the actual label is also 0, the loss for that training example is 0. 
* However, when the model prediction is close to 1 ($h(z(\theta)) = 0.9999$) and the label is 0, the second term of the log loss becomes a large negative number, which is then multiplied by the overall factor of -1 to convert it to a positive loss value. $-1 \times (1 - 0) \times log(1 - 0.9999) \approx 9.2$ The closer the model prediction gets to 1, the larger the loss.

In [12]:
# verify that when the model predicts close to 1, but the actual label is 0, the loss is a large positive value
-1 * (1 - 0) * np.log(1 - 0.9999) # loss is about 9.2

9.210340371976294

* Likewise, if the model predicts close to 0 ($h(z) = 0.0001$) but the actual label is 1, the first term in the loss function becomes a large number: $-1 \times log(0.0001) \approx 9.2$.  The closer the prediction is to zero, the larger the loss.

In [13]:
# verify that when the model predicts close to 0 but the actual label is 0, the loss is a large positive value
-1 * np.log(0.0001) # loss is about 9.2

9.210340371976182

#### Update the weights

To update your weight vector $\theta$, you will apply gradient descent to iteratively improve your model's predictions.  
The gradient of the cost function $J$ with respect to one of the weights $\theta_j$ is:

$$\nabla_{\theta_j}J(\theta) = \frac{1}{m} \sum_{i=1}^m(h^{(i)}-y^{(i)})x_j \tag{5}$$
* 'i' is the index across all 'm' training examples.
* 'j' is the index of the weight $\theta_j$, so $x_j$ is the feature associated with weight $\theta_j$

* To update the weight $\theta_j$, we adjust it by subtracting a fraction of the gradient determined by $\alpha$:
$$\theta_j = \theta_j - \alpha \times \nabla_{\theta_j}J(\theta) $$
* The learning rate $\alpha$ is a value that we choose to control how big a single update will be.


## Instructions: Implement gradient descent function
* The number of iterations `num_iters` is the number of times that you'll use the entire training set.
* For each iteration, you'll calculate the cost function using all training examples (there are `m` training examples), and for all features.
* Instead of updating a single weight $\theta_i$ at a time, we can update all the weights in the column vector:  
$$\mathbf{\theta} = \begin{pmatrix}
\theta_0
\\
\theta_1
\\ 
\theta_2 
\\ 
\vdots
\\ 
\theta_n
\end{pmatrix}$$
* $\mathbf{\theta}$ has dimensions (n+1, 1), where 'n' is the number of features, and there is one more element for the bias term $\theta_0$ (note that the corresponding feature value $\mathbf{x_0}$ is 1).
* The 'logits', 'z', are calculated by multiplying the feature matrix 'x' with the weight vector 'theta'.  $z = \mathbf{x}\mathbf{\theta}$
    * $\mathbf{x}$ has dimensions (m, n+1) 
    * $\mathbf{\theta}$: has dimensions (n+1, 1)
    * $\mathbf{z}$: has dimensions (m, 1)
* The prediction 'h', is calculated by applying the sigmoid to each element in 'z': $h(z) = sigmoid(z)$, and has dimensions (m,1).
* The cost function $J$ is calculated by taking the dot product of the vectors 'y' and 'log(h)'.  Since both 'y' and 'h' are column vectors (m,1), transpose the vector to the left, so that matrix multiplication of a row vector with column vector performs the dot product.
$$J = \frac{-1}{m} \times \left(\mathbf{y}^T \cdot log(\mathbf{h}) + \mathbf{(1-y)}^T \cdot log(\mathbf{1-h}) \right)$$
* The update of theta is also vectorized.  Because the dimensions of $\mathbf{x}$ are (m, n+1), and both $\mathbf{h}$ and $\mathbf{y}$ are (m, 1), we need to transpose the $\mathbf{x}$ and place it on the left in order to perform matrix multiplication, which then yields the (n+1, 1) answer we need:
$$\mathbf{\theta} = \mathbf{\theta} - \frac{\alpha}{m} \times \left( \mathbf{x}^T \cdot \left( \mathbf{h-y} \right) \right)$$

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li>use np.dot for matrix multiplication.</li>
    <li>To ensure that the fraction -1/m is a decimal value, cast either the numerator or denominator (or both), like `float(1)`, or write `1.` for the float version of 1. </li>
</ul>
</p>



In [14]:
# UNQ_C2 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def gradientDescent(x, y, theta, alpha, num_iters):
    '''
    Input:
        x: matrix of features which is (m,n+1)
        y: corresponding labels of the input matrix x, dimensions (m,1)
        theta: weight vector of dimension (n+1,1)
        alpha: learning rate
        num_iters: number of iterations you want to train your model for
    Output:
        J: the final cost
        theta: your final weight vector
    Hint: you might want to print the cost to make sure that it is going down.
    '''
    

In [4]:
# Check the function
# Construct a synthetic test case using numpy PRNG functions

# X input is 10 x 3 with ones for the bias terms

# Y Labels are 10 x 1


# Apply gradient descent


#### Expected output
```
The cost after training is 0.67094970.
The resulting vector of weights is [4.1e-07, 0.00035658, 7.309e-05]
```

## Part 2: Extracting the features

* Given a list of tweets, extract the features and store them in a matrix. You will extract two features.
    * The first feature is the number of positive words in a tweet.
    * The second feature is the number of negative words in a tweet. 
* Then train your logistic regression classifier on these features.
* Test the classifier on a validation set. 

### Instructions: Implement the extract_features function. 
* This function takes in a single tweet.
* Process the tweet using the imported `process_tweet()` function and save the list of tweet words.
* Loop through each word in the list of processed words
    * For each word, check the `freqs` dictionary for the count when that word has a positive '1' label. (Check for the key (word, 1.0)
    * Do the same for the count for when the word is associated with the negative label '0'. (Check for the key (word, 0.0).)


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li>Make sure you handle cases when the (word, label) key is not found in the dictionary. </li>
    <li> Search the web for hints about using the `.get()` method of a Python dictionary.  Here is an <a href="https://www.programiz.com/python-programming/methods/dictionary/get" > example </a> </li>
</ul>
</p>


In [16]:
# UNQ_C3 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def extract_features(tweet, freqs):
    '''
    Input: 
        tweet: a list of words for one tweet
        freqs: a dictionary corresponding to the frequencies of each tuple (word, label)
    Output: 
        x: a feature vector of dimension (1,3)
    '''

In [5]:
# Check your function

# test 1
# test on training data


#### Expected output
```
[[1.00e+00 3.02e+03 6.10e+01]]
```

In [6]:
# test 2:
# check for when the words are not in the freqs dictionary


#### Expected output
```
[[1. 0. 0.]]
```

## Part 3: Training Your Model

To train the model:
* Stack the features for all training examples into a matrix `X`. 
* Call `gradientDescent`, which you've implemented above.

This section is given to you.  Please read it for understanding and run the cell.

In [7]:
# collect the features 'x' and stack them into a matrix 'X'


# training labels corresponding to X

# Apply gradient descent


**Expected Output**: 

```
The cost after training is 0.24216529.
The resulting vector of weights is [7e-08, 0.0005239, -0.00055517]
```

# Part 4: Test your logistic regression

It is time for you to test your logistic regression function on some new input that your model has not seen before. 

#### Instructions: Write `predict_tweet`
Predict whether a tweet is positive or negative.

* Given a tweet, process it, then extract the features.
* Apply the model's learned weights on the features to get the logits.
* Apply the sigmoid to the logits to get the prediction (a value between 0 and 1).

$$y_{pred} = sigmoid(\mathbf{x} \cdot \theta)$$

In [76]:
lr.predict_proba([extract_features(preprocess_tweet(x_test[2]))])

array([[3.37774253e-12, 1.00000000e+00]])

In [73]:
# UNQ_C4 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def predict_tweet(tweet, model):
    '''
    Input: 
        tweet: a string
        model: trained model
    Output: the probability of a tweet being positive or negative
    '''
    return model.predict_proba([extract_features(preprocess_tweet(tweet))])

In [90]:
lr.coef_

array([[ 0.27177522,  0.00873689, -0.01001496]])

In [84]:
# Run this cell to test your function
for tweet in ['I am happy', 'I am bad', 'this movie should have been great.', 'great', 'great great', 'great great great', 'great great great great']:
    print( f'{tweet} -> {predict_tweet(tweet, lr)[0]} -> {lr.predict([extract_features(preprocess_tweet(tweet))])}')

I am happy -> [0.12609435 0.87390565] -> [1.]
I am bad -> [0.46659585 0.53340415] -> [1.]
this movie should have been great. -> [0.1687119 0.8312881] -> [1.]
great -> [0.17057416 0.82942584] -> [1.]
great great -> [0.17057416 0.82942584] -> [1.]
great great great -> [0.17057416 0.82942584] -> [1.]
great great great great -> [0.17057416 0.82942584] -> [1.]


**Expected Output**: 
```
I am happy -> 0.518580
I am bad -> 0.494339
this movie should have been great. -> 0.515331
great -> 0.515464
great great -> 0.530898
great great great -> 0.546273
great great great great -> 0.561561
```

In [132]:
# Feel free to check the sentiment of your own tweet below
my_tweet = 'I am learning :)'
predict_tweet(my_tweet, lr)[0]

array([3.40039108e-12, 1.00000000e+00])

## Check performance using the test set
After training your model using the training set above, check how your model might perform on real, unseen data, by testing it against the test set.

#### Instructions: Implement `test_logistic_regression` 
* Given the test data and the weights of your trained model, calculate the accuracy of your logistic regression model. 
* Use your `predict_tweet()` function to make predictions on each tweet in the test set.
* If the prediction is > 0.5, set the model's classification `y_hat` to 1, otherwise set the model's classification `y_hat` to 0.
* A prediction is accurate when `y_hat` equals `test_y`.  Sum up all the instances when they are equal and divide by `m`.


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li>Use np.asarray() to convert a list to a numpy array</li>
    <li>Use np.squeeze() to make an (m,1) dimensional array into an (m,) array </li>
</ul>
</p>

In [118]:
# UNQ_C5 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def test_logistic_regression(test_x, test_y, model):
    """
    Input: 
        test_x: a list of tweets
        test_y: (m, 1) vector with the corresponding labels for the list of tweets
        model: Trained Logistic Regression Model
    Output: 
        accuracy: (# of tweets classified correctly) / (total # of tweets)
    """
    y_pred = model.predict([extract_features(preprocess_tweet(tweet)) for tweet in test_x])
    
    print('Confusion Matrix: \n', confusion_matrix(test_y, y_pred))
    print(classification_report(test_y, y_pred))
    
    return sum([x==y for x,y in zip(y_pred, test_y)]) / len(test_y)

In [130]:
# Print accuracy
test_logistic_regression(x_test, y_test, lr)

Confusion Matrix: 
 [[993   7]
 [  6 994]]
              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99      1000
         1.0       0.99      0.99      0.99      1000

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000



0.9935

#### Expected Output: 
```0.9950```  
Pretty good!

# Part 5: Error Analysis

In this part you will see some tweets that your model misclassified. Why do you think the misclassifications happened? Specifically what kind of tweets does your model misclassify?

In [134]:
# Some error analysis done for you
print('Label Predicted Tweet')
for x,y in zip(x_test, y_test):
    y_hat = predict_tweet(x, lr)[0,1]

    if np.abs(y - (y_hat > 0.5)) > 0:
        print('THE TWEET IS:', x)
        print('THE PROCESSED TWEET IS:', preprocess_tweet(x))
        print('%d\t%0.8f\t%s' % (y, y_hat, ' '.join(preprocess_tweet(x)).encode('ascii', 'ignore')))

Label Predicted Tweet
THE TWEET IS: I'm playing Brain Dots : ) #BrainDots
http://t.co/cHl12JvuxN http://t.co/GGgU9PYEjI
THE PROCESSED TWEET IS: ["i'm", 'play', 'brain', 'dot', 'braindot', 't.co/chl12jvuxn', 't.co/gggu9pyeji']
1	0.36376919	b"i'm play brain dot braindot t.co/chl12jvuxn t.co/gggu9pyeji"
THE TWEET IS: I'm playing Brain Dots : ) #BrainDots
http://t.co/MifDDs7CQS http://t.co/WtIWoeATPj
THE PROCESSED TWEET IS: ["i'm", 'play', 'brain', 'dot', 'braindot', 't.co/mifdds7cq', 't.co/wtiwoeatpj']
1	0.36376919	b"i'm play brain dot braindot t.co/mifdds7cq t.co/wtiwoeatpj"
THE TWEET IS: I still fully intend to write as many game designs as possible while there. And an attack plan for the next 6 months. &gt;:D
THE PROCESSED TWEET IS: ['still', 'fulli', 'intend', 'write', 'mani', 'game', 'design', 'possibl', 'attack', 'plan', 'next', '6', 'month', '>:d']
1	0.47590703	b'still fulli intend write mani game design possibl attack plan next 6 month >:d'
THE TWEET IS: Remember that one time I d

Later in this specialization, we will see how we can use deep learning to improve the prediction performance.

# Part 6: Predict with your own tweet

In [136]:
# Feel free to change the tweet below
my_tweet = 'This is a ridiculously bright movie. The plot was terrible and I was sad until the ending!'
print(preprocess_tweet(my_tweet))
y_hat = predict_tweet(my_tweet, lr)[0,1]
print(y_hat)
if y_hat > 0.5:
    print('Positive sentiment')
else: 
    print('Negative sentiment')

['ridicul', 'bright', 'movi', 'plot', 'terribl', 'sad', 'end']
0.3171086659548087
Negative sentiment
